### ISSUE TITLE
DSM 7.0 이후 OTP 로그인이 안됩니다. 

### ISSUE THREAD

**Issue by romantech** [acidpop/synobot#12]
안녕하세요, 
먼저 유용한 Bot 개발해주셔서 감사합니다. 평소 잘 사용하고 있습니다 :)

DSM 7.0 버전 업데이트이후 DSM에 OTP를 설정했다면 Synobot DSM 로그인이 안됩니다. 
OTP를 해제하면 Synobot의 DSM 로그인 잘 되구요. 
참고로 DSM 6.x 버전대에선 OTP를 설정했어도 Synobot DSM 로그인시 OTP 번호를 입력하면 잘 됐었습니다. 

![image](https://user-images.githubusercontent.com/8604840/124341406-0c052180-dbf7-11eb-998f-c27c4a6be650.png)

해결 방법이 없을까요?

**Comment by acidpop** [comment]
안녕하세요

제가 아직 DMS 7.0 으로 올리지를 않아서 테스트가 안되고 있습니다.

혹시 아래 커맨드 결과를 받아 볼수 있을까요?

아래와 같은 환경이라면

NAS IP : 192.168.0.2
Download Station Port : 8088

curl -k -v "https://192.168.0.2:8088//webapi/auth.cgi?api=SYNO.API.Auth&version=3&method=login&account=계정&passwd=계정비밀번호&session=DownloadStation&format=cookie"

URL 주소에서 IP, Port 부분 변경하여 주시고

한글로 계정, 계정비밀번호 라고 쓰여 있는곳만 사용하시는 계정으로 변경해서 시험해주시면 됩니다.


나오는 결과 중에 error 부분의 code 부분이 있을거에요

아니면 전체 내용을 다 보내주셔도 됩니다

**Comment by Sisquaker** [comment]
저도 동일한 증상이기에 위 내용대로 실행하여 코드 올려드립니다.

* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
> GET //webapi/auth.cgi?api=SYNO.API.Auth&version=3&method=login&account=***&                                                          passwd=***&session=DownloadStation&format=cookie HTTP/2
> Host: ***:****
> user-agent: curl/7.75.0
> accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
< HTTP/2 200
< server: nginx
< date: Tue, 06 Jul 2021 12:34:08 GMT
< content-type: application/json; charset="UTF-8"
< vary: Accept-Encoding
< x-content-type-options: nosniff
< x-xss-protection: 1; mode=block
< cache-control: max-age=0, no-cache, no-store, must-revalidate
< pragma: no-cache
< expires: 0
<
{"error":{"code":403,"errors":{"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ                                                          hdWQiOiIyRkEiLCJleHAiOjE2MjU1NzUxNDcsImlhdCI6MTYyNTU3NDg0Nywic3ViIjoibmVyb25lIn0                                                          .efYwZk-CrF7BLGor1A8fB1VEd9EnUnW_HY-H10Ec7Gk","types":[{"type":"authenticator"},  


추측컨대 OTP에서 문제가 발생하는 듯 한데...

**Comment by acidpop** [comment]
원인은 찾았습니다
기존 6.x 에서는 otp 에러인 경우 402를 보냈었는데
7.0 은 403을 보내네요

제가 당장은 시간이 안되서 시간 되는데로 업데이트 하겠습니다

**Comment by romantech** [comment]
저도 명령어를 실행해봤는데 `400`에러를 보냅니다.
혹시 몰라 출력 결과 첨부합니다. 

```shell
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 200 
< date: Tue, 06 Jul 2021 13:02:41 GMT
< content-type: application/json; charset="UTF-8"
< vary: Accept-Encoding
< p3p: CP="IDC DSP COR ADM DEVi TAIi PSA PSD IVAi IVDi CONi HIS OUR IND CNT"
< x-content-type-options: nosniff
< x-xss-protection: 1; mode=block
< set-cookie: did=생략;expires=Thu, 05-Aug-2021 13:02:35 GMT;path=/;HttpOnly
< x-content-type-options: nosniff
< x-xss-protection: 1; mode=block
< cache-control: max-age=0, no-cache, no-store, must-revalidate
< pragma: no-cache
< expires: 0
< 
* Connection #0 to host down.romantech.net left intact
{"error":{"code":400},"success":false}* Closing connection 0
```

**Comment by acidpop** [comment]
> 저도 명령어를 실행해봤는데 `400`에러를 보냅니다.
> 혹시 몰라 출력 결과 첨부합니다.
> 
> ```shell
> * Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
> < HTTP/2 200 
> < date: Tue, 06 Jul 2021 13:02:41 GMT
> < content-type: application/json; charset="UTF-8"
> < vary: Accept-Encoding
> < p3p: CP="IDC DSP COR ADM DEVi TAIi PSA PSD IVAi IVDi CONi HIS OUR IND CNT"
> < x-content-type-options: nosniff
> < x-xss-protection: 1; mode=block
> < set-cookie: did=생략;expires=Thu, 05-Aug-2021 13:02:35 GMT;path=/;HttpOnly
> < x-content-type-options: nosniff
> < x-xss-protection: 1; mode=block
> < cache-control: max-age=0, no-cache, no-store, must-revalidate
> < pragma: no-cache
> < expires: 0
> < 
> * Connection #0 to host 생략 left intact
> {"error":{"code":400},"success":false}* Closing connection 0
> ```

400 에러는 문서를 보니 ID 또는 Password 가 잘못된 경우라고 나옵니다.

**Comment by acidpop** [comment]
제 NAS 에서 7.0 업데이트 후 OTP 설정 하였고

해당 원인 부분 수정 후 테스트 하였습니다.

0.12 버전으로 업데이트 하여 주시고 혹여 안되면 다시 한번 이슈로 추가 하여 주시면 감사하겠습니다.
