### ISSUE TITLE
Secure SignIn 사용시

### ISSUE THREAD

**Issue by sili96885** [acidpop/synobot#16]
안녕하세요! 문의 드립니다. 
처음 세팅해보는 유저입니다. 
헌데 저는 왜 제가 설정한 bot 에서 메세지가 전혀 오지 않는걸까요? 보통 오류메세지라도 와야하는게 아닌지...? 전혀 오질 않네요.
Secure SignIn 사용이 문제가 되는건지 알고 싶습니다. 

감사합니다!

**Comment by acidpop** [comment]
안녕하세요
도커의 로그 내용을 같이 올려주시면 원인 분석에 도움이 됩니다.
