### ISSUE TITLE
다운로드가 자동으로 시작되지 않습니다.

### ISSUE THREAD

**Issue by thomas0812** [acidpop/synobot#17]
https://gofile.me/6YiCv/ivVtSjV5o

로그 링크입니다.

일단 증상은 제가 보낸 토렌트 파일이 정상적으로 /tor_watch 폴더로 들어가는데, 다운로드 스테이션에서 작업이 시작되지 않습니다.
위 로그 중에 다운로드 stat가 조회되는 로그가 있는데, 이거는 제가 웹으로 다운로드 스테이션에 직접 올린뒤 /stat 등의 명령어가 정상동작하는지 test 해본 이력입니다....

**Comment by acidpop** [comment]
다운로드 스테이션의 감시 폴더로 지정한 위치에 토렌트 파일을 올리면 정상적으로 시작 되나요?
synobot 은 watch 경로에 토렌트파일만 올리는게 끝이고 따로 토렌트 작업 시작을 요청하지는 않습니다.
