### ISSUE TITLE
토렌트 다운 완료 시 shell을 실행할 수 있나요?

### ISSUE THREAD

**Issue by backs99** [acidpop/synobot#18]
안녕하세요.
현재 저는 synobot을 정말 유용하게 사용하고 있습니다.
synobot에 토렌트 다운이 완료 되면 shell을 실행하는 기능이 있으면 좋을 듯하여 문의 드립니다.

토렌트로 영화 다운이 완료 되면 ${TR_TORRENT_NAME} 파라미터를 전달받아 지정된 폴더에 있는 자막파일을 찾아서 복사하고 영상이름과 동일하게 변경하는 shell을 만들어 사용했습니다.
헌데 최근 DSM 업데이트 이후 ds download에서 다운완료 후 shell을 실행하는 기능이 안되는듯 합니다.

하여 토렌트 다운이 완료 됐을 때 파라미터로 전달받은 다운받은 폴더에 사용자가 지정한 특정 폴더에서 유사한 자막파일이 이동 되도록 하거나 아니면 지정한 shell을 실행하도록 하는 기능을 제공해 주실 수 있을까요?
(필요 파라미터 : TR_TORRENT_NAME)

만들어 주신 노고에 정말 감사드립니다.
항상 즐거운 나날 되세요.

**Comment by acidpop** [comment]
안녕하세요
synobit 이 docker 내부에서 실행이 되는 소비스여서
스크립트를 수행하여도 원하시는 작업을 수행하기에는 무리가 있습니다

실제로 시놀로지 nas 의 디스크에 직접 접근하는게 아니기 때문에 원하시는 기능은 어렵습니다
