### ISSUE TITLE
DSM 7.2 환경 실행 문의

### ISSUE THREAD

**Issue by caravan-icaner** [acidpop/synobot#24]
현재 DSM 7.2에서 정상 동작 되나요? 로그를 보니 DSM 로긴이 안되는거 같아서 문의 드립니다.

그리고 저는 단일 단계 인증을 사용해서 2단계 인증은 사용하지 않는데 그래서 로그인이 안되는지도 궁금합니다.

![스크린샷 2023-05-30 205828](https://github.com/acidpop/synobot/assets/111466772/33c9db63-b27e-4131-95ad-08e6984d06a9)

**Comment by acidpop** [comment]
증상만 봐서는 알수 없습니다~!
저도 7.2 설치후 실행해보았는데 정상 작동 하고 있네요

Container Manager -> 컨테이너 -> synobot 선택 -> 로그 부분의 내용을 올려주시면 어떤 오류인지 확인하는데 도움이 됩니다.

**Comment by caravan-icaner** [comment]
로그인 할때 텔레그램으로 DSM 암호를 묻는 알람 메세지가 오질 않습니다. 텔레그램에서 api 등록하고 hello world 메세지까지는 웹창에서 확인은 완료한 상태 입니다. (https://lamanus.kr/4)

![image](https://github.com/acidpop/synobot/assets/111466772/a7c1ec4b-b018-4d48-8945-d35ec45745c8)

**Comment by caravan-icaner** [comment]
아래 문서를 확인해보니 192.168.x.x  로 접속을 해보니 접속은 되네요

https://www.clien.net/service/board/cm_nas/15507361


![image](https://github.com/acidpop/synobot/assets/111466772/137eb143-2c1a-4bfc-971b-773e288f5a45)

**Comment by caravan-icaner** [comment]
방화벽 문제인것 같네요. 제가 처리해할 부분인것 같습니다.

**Comment by caravan-icaner** [comment]
방화벽에서 설정에 사용되는 포트 8000 번 외에 다른어떤 부분을 오픈해야 하나요??
아예 방화벽을 끄기까 되긴하는데 8000번 포트를 허용해서는 실행이 안되는것 같습니다.

**Comment by caravan-icaner** [comment]
테스트 해보니까 저는 192.168.1.0~255까지 오픈을 해놨는데 synobot에서 사용하는 아이피 대역이 다른것 같습니다.
어떤 주소를 오픈해야 하는지 알려주시면 해결이 될것 같습니다. 답변 부탁드릴께요 감사합니다.

**Comment by caravan-icaner** [comment]
찾았습니다.  172.16.0.0 / 255.240.0.0 만 오픈하면 되네요 ^^
