### ISSUE TITLE
파일 등록 안됨 

### ISSUE THREAD

**Issue by khaisis** [acidpop/synobot#8]
안녕하세요
우연찮게 검색하다가 알아서 한번 사용해보고 있습니다. ㅎㅎ

안되는 부분은 HTTPS (사설 인증서 사용 중)로 해서 로그인하고
토렌트 파일을 인식하고 봇이 torrent 파일 다운로드 하고 
텔레그램으로 파일이 등록되었다고 알람은 오는데
확인해 보면 등록은 안되있네요

https://127.0.0.1에 DSM_CERT=0 로 주었구요.

로그 파일에 아레와 같이 찍혀있네요.

2020-05-21 23:41:11 [ERROR] CreateTaskForFile|synology rest api request Connection Error                                                                        
2020-05-21 23:41:11 [INFO] File Received, file name : xxxxx.torrent 

이미지는 synobot 검색에서 lastest 로 설치했구요.
DSM 버전 : 6.2.3-25426
Download Station 버전 : 3.8.14-3543 입니다.
참고로 http로는 잘되네요.

감사합니다.

**Comment by acidpop** [comment]
혹시 python 실행 하셔서

다음 코드 실행 해보실수 있을까요?

import requests

id = '사용자ID'
pw = '비밀번호'
params = {'api' : 'SYNO.API.Auth', 'version' : '2', 'method' : 'login' , 'account' : id, 'passwd' : pw, 'session' : 'DownloadStation', 'format' : 'cookie'}

url = 'https://127.0.0.1:8000/webapi/auth.cgi'

res = requests.get(url, params=params, verify=False)


id 와 pw , 그리고 url 부분에 포트만 환경에 맞춰서 실행 하시면 됩니다.

**Comment by acidpop** [comment]
파일 등록하는 코드에서 인증서 무시 옵션이 누락 되어 있었습니다.

0.8 버전에 수정 완료.
